function mapUser(row) {
  if (!row) return null;
  if (row.name !== undefined) return {
    id: row.id,
    name: row.name,
    email: row.email,
    rollNumber: row.rollNumber || '',
    cgpa: row.cgpa || '',
    degree: row.degree || '',
    college: row.college || '',
    course: row.course || row.degree || '',
    graduationYear: row.graduationYear || null,
    targetRole: row.targetRole || '',
    skillLevel: row.skillLevel || 'Beginner',
    notificationsEnabled: row.notificationsEnabled ?? true,
    xp: row.xp || 0,
  };
  return { id: row.id, name: row.full_name, email: row.email, rollNumber: row.roll_number, cgpa: row.cgpa == null ? '' : String(row.cgpa), degree: row.degree, college: row.college, course: row.course, graduationYear: row.graduation_year, targetRole: row.target_role, skillLevel: row.skill_level, notificationsEnabled: row.notifications_enabled, xp: row.xp };
}
function mapTask(row) {
  return { id: row.id, userId: row.user_id, title: row.title, description: row.description, category: row.category, priority: row.priority, dueDate: row.due_date, estimatedMinutes: row.estimated_minutes, status: row.status, xp: row.xp, completed: row.status === 'Completed', createdAt: row.created_at, completedAt: row.completed_at };
}
function mapQuestion(row) {
  return { id: row.id, question: row.question, options: [row.option_a, row.option_b, row.option_c, row.option_d], category: row.category, topic: row.topic, difficulty: row.difficulty, explanation: row.explanation };
}

class PostgresStore {
  constructor(database) { this.pool = database.pool; }
  health() { return this.pool.query('SELECT 1').then(() => 'ok'); }
  close() { return this.pool.end(); }
  async findUserByEmail(email) { const { rows } = await this.pool.query('SELECT u.id, u.email, u.password_hash, u.password_salt, p.full_name, p.roll_number, p.cgpa, p.degree, p.college, p.course, p.graduation_year, p.target_role, p.skill_level, s.daily_reminders AS notifications_enabled, pr.xp FROM users u JOIN profiles p ON p.user_id = u.id JOIN user_settings s ON s.user_id = u.id JOIN user_progress pr ON pr.user_id = u.id WHERE u.email = $1', [email]); return rows[0] || null; }
  async findUserById(userId) { const { rows } = await this.pool.query('SELECT u.id, u.email, p.full_name, p.roll_number, p.cgpa, p.degree, p.college, p.course, p.graduation_year, p.target_role, p.skill_level, s.daily_reminders AS notifications_enabled, pr.xp FROM users u JOIN profiles p ON p.user_id = u.id JOIN user_settings s ON s.user_id = u.id JOIN user_progress pr ON pr.user_id = u.id WHERE u.id = $1', [userId]); return rows[0] || null; }
  async createUser(user) {
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN');
      await client.query('INSERT INTO users (id, email, password_hash, password_salt) VALUES ($1, $2, $3, $4)', [user.id, user.email, user.hash, user.salt]);
      await client.query('INSERT INTO profiles (user_id, full_name, college, course, graduation_year, target_role, skill_level, degree) VALUES ($1,$2,$3,$4,$5,$6,$7,$4)', [user.id, user.name, user.college, user.course, user.graduationYear, user.targetRole, user.skillLevel]);
      await client.query('INSERT INTO user_settings (user_id) VALUES ($1)', [user.id]);
      await client.query('INSERT INTO user_progress (user_id, xp) VALUES ($1, 0)', [user.id]);
      const starter = [['Solve 10 Profit & Loss Aptitude questions', 'Aptitude', 15], ['Practice 2 Hard Tree Traversal coding problems', 'Coding & DSA', 25], ['Revise Operating System Deadlocks & Semaphores', 'Tech Core', 20]];
      for (const [title, category, xp] of starter) await client.query('INSERT INTO tasks (user_id, title, category, xp) VALUES ($1,$2,$3,$4)', [user.id, title, category, xp]);
      await client.query('COMMIT'); return user;
    } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
  }
  async updateUser(userId, values) {
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN');
      const profileFields = { name: 'full_name', rollNumber: 'roll_number', cgpa: 'cgpa', degree: 'degree', college: 'college', course: 'course', graduationYear: 'graduation_year', targetRole: 'target_role', skillLevel: 'skill_level' };
      for (const [field, column] of Object.entries(profileFields)) if (values[field] !== undefined) await client.query(`UPDATE profiles SET ${column} = $1, updated_at = now() WHERE user_id = $2`, [values[field], userId]);
      if (values.notificationsEnabled !== undefined) await client.query('UPDATE user_settings SET daily_reminders = $1, updated_at = now() WHERE user_id = $2', [values.notificationsEnabled, userId]);
      await client.query('COMMIT'); return this.findUserById(userId);
    } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
  }
  async createNotification(notification) { const { rows } = await this.pool.query('INSERT INTO notifications (user_id,type,title,message,related_entity_type,related_entity_id) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING RETURNING id,user_id,type,title,message,related_entity_type,related_entity_id,is_read,created_at,read_at', [notification.userId, notification.type, notification.title, notification.message, notification.relatedEntityType || null, notification.relatedEntityId || null]); return rows[0] || null; }
  async listNotifications(userId) { const { rows } = await this.pool.query('SELECT id,user_id,type,title,message,related_entity_type,related_entity_id,is_read,created_at,read_at FROM notifications WHERE user_id = $1 ORDER BY created_at DESC', [userId]); return rows; }
  async unreadNotificationCount(userId) { const { rows } = await this.pool.query('SELECT count(*)::int AS count FROM notifications WHERE user_id = $1 AND is_read = false', [userId]); return rows[0].count; }
  async markNotificationRead(userId, notificationId) { const { rows } = await this.pool.query('UPDATE notifications SET is_read = true, read_at = now() WHERE id = $1 AND user_id = $2 RETURNING id,user_id,type,title,message,related_entity_type,related_entity_id,is_read,created_at,read_at', [notificationId, userId]); return rows[0] || null; }
  async markAllNotificationsRead(userId) { const result = await this.pool.query('UPDATE notifications SET is_read = true, read_at = now() WHERE user_id = $1 AND is_read = false', [userId]); return result.rowCount; }
  async listTasks(userId) { const { rows } = await this.pool.query('SELECT * FROM tasks WHERE user_id = $1 ORDER BY created_at DESC', [userId]); return rows.map(mapTask); }
  async createTask(task) { const { rows } = await this.pool.query('INSERT INTO tasks (id,user_id,title,description,category,priority,due_date,estimated_minutes,xp) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *', [task.id, task.userId, task.title, task.description, task.category, task.priority, task.dueDate, task.estimatedMinutes, task.xp]); return mapTask(rows[0]); }
  async updateTask(userId, taskId, values) { const current = await this.pool.query('SELECT * FROM tasks WHERE id = $1 AND user_id = $2', [taskId, userId]); if (!current.rows[0]) return null; const task = current.rows[0]; const completed = values.completed === undefined ? task.status === 'Completed' : Boolean(values.completed); const { rows } = await this.pool.query('UPDATE tasks SET title=$1, description=$2, category=$3, priority=$4, due_date=$5, estimated_minutes=$6, status=$7, completed_at=$8 WHERE id=$9 AND user_id=$10 RETURNING *', [values.title || task.title, values.description ?? task.description, values.category || task.category, values.priority || task.priority, values.dueDate ?? task.due_date, values.estimatedMinutes ?? task.estimated_minutes, completed ? 'Completed' : 'Pending', completed ? new Date() : null, taskId, userId]); return mapTask(rows[0]); }
  async deleteTask(userId, taskId) { const result = await this.pool.query('DELETE FROM tasks WHERE id = $1 AND user_id = $2', [taskId, userId]); return result.rowCount === 1; }
  async createPracticeAttempt(attempt) { const { rows } = await this.pool.query('INSERT INTO practice_attempts (id,user_id,topic,score,total,time_spent_seconds) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *', [attempt.id, attempt.userId, attempt.topic, attempt.score, attempt.total, attempt.timeSpentSeconds || 0]); return rows[0]; }
  async listPracticeAttempts(userId) { const { rows } = await this.pool.query('SELECT * FROM practice_attempts WHERE user_id = $1 ORDER BY completed_at DESC', [userId]); return rows; }
  async createMockAttempt(attempt) { const { rows } = await this.pool.query('INSERT INTO mock_attempts (id,user_id,title,score,total,time_spent_seconds) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *', [attempt.id, attempt.userId, attempt.title, attempt.score, attempt.total, attempt.timeSpentSeconds || 0]); return rows[0]; }
  async listMockAttempts(userId) { const { rows } = await this.pool.query('SELECT * FROM mock_attempts WHERE user_id = $1 ORDER BY completed_at DESC', [userId]); return rows; }
  async listQuestions(filters) { const values = []; const conditions = []; for (const [field, column] of [['category', 'category'], ['topic', 'topic'], ['difficulty', 'difficulty']]) { if (filters[field]) { values.push(filters[field]); conditions.push(`${column} = $${values.length}`); } } values.push(Math.min(filters.limit || 10, 50)); const { rows } = await this.pool.query(`SELECT id,question,option_a,option_b,option_c,option_d,category,topic,difficulty,explanation FROM practice_questions ${conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''} ORDER BY created_at LIMIT $${values.length}`, values); return rows.map(mapQuestion); }
  async getQuestion(questionId) { const { rows } = await this.pool.query('SELECT id,question,option_a,option_b,option_c,option_d,category,topic,difficulty,explanation,correct_answer FROM practice_questions WHERE id = $1', [questionId]); return rows[0] || null; }
  async createPracticeSession(session, answers) { const client = await this.pool.connect(); try { await client.query('BEGIN'); const sessionId = session.id; let score = 0; for (const answer of answers) { const question = await client.query('SELECT correct_answer FROM practice_questions WHERE id = $1', [answer.questionId]); if (!question.rows[0]) throw new Error('Invalid practice question'); const correct = question.rows[0].correct_answer === answer.selectedAnswer; if (correct) score += 1; await client.query('INSERT INTO practice_answers (session_id,question_id,selected_answer,correct,time_taken_seconds) VALUES ($1,$2,$3,$4,$5)', [sessionId, answer.questionId, answer.selectedAnswer || null, correct, answer.timeTakenSeconds || 0]); } const { rows } = await client.query('INSERT INTO practice_sessions (id,user_id,category,topic,difficulty,question_count,score,total,time_spent_seconds) VALUES ($1,$2,$3,$4,$5,$6,$7,$6,$8) RETURNING *', [sessionId, session.userId, session.category, session.topic || '', session.difficulty || 'Medium', answers.length, score, session.timeSpentSeconds || 0]); await client.query('INSERT INTO practice_attempts (id,user_id,topic,score,total,time_spent_seconds) VALUES ($1,$2,$3,$4,$5,$6)', [sessionId, session.userId, session.topic || session.category, score, answers.length, session.timeSpentSeconds || 0]); await client.query('COMMIT'); return rows[0]; } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async listPracticeHistory(userId) { const { rows } = await this.pool.query('SELECT * FROM practice_sessions WHERE user_id = $1 ORDER BY completed_at DESC', [userId]); return rows; }
  async listMockTests() { const { rows } = await this.pool.query('SELECT id,title,description,duration_minutes,question_count,difficulty,category,created_at FROM mock_tests WHERE is_published = true ORDER BY created_at DESC'); return rows; }
  async getMockTest(testId) { const { rows } = await this.pool.query('SELECT id,title,description,duration_minutes,question_count,difficulty,category,created_at FROM mock_tests WHERE id = $1 AND is_published = true', [testId]); return rows[0] || null; }
  async getMockQuestions(testId) { const { rows } = await this.pool.query('SELECT q.id,q.question,q.option_a,q.option_b,q.option_c,q.option_d,q.category,q.topic,q.difficulty,mq.position FROM mock_questions mq JOIN practice_questions q ON q.id = mq.question_id WHERE mq.mock_test_id = $1 ORDER BY mq.position', [testId]); return rows.map(mapQuestion); }
  async createMockResult(result, answers) { const client = await this.pool.connect(); try { await client.query('BEGIN'); let score = 0; for (const answer of answers) { const question = await client.query('SELECT correct_answer FROM practice_questions WHERE id = $1', [answer.questionId]); if (!question.rows[0]) throw new Error('Invalid mock question'); const correct = question.rows[0].correct_answer === answer.selectedAnswer; if (correct) score += 1; await client.query('INSERT INTO mock_attempt_answers (attempt_id,question_id,selected_answer,correct,marked_for_review) VALUES ($1,$2,$3,$4,$5)', [result.id, answer.questionId, answer.selectedAnswer || null, correct, answer.markedForReview || false]); } const { rows } = await client.query('INSERT INTO mock_attempts (id,user_id,mock_test_id,title,score,total,time_spent_seconds) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *', [result.id, result.userId, result.mockTestId, result.title, score, answers.length, result.timeSpentSeconds || 0]); await client.query('COMMIT'); return rows[0]; } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async analytics(userId, offsetMinutes = 0) {
    const [taskResult, practiceResult, mockResult, categoryResult, topicResult] = await Promise.all([
      this.pool.query('SELECT status, due_date, completed_at FROM tasks WHERE user_id = $1', [userId]),
      this.pool.query('SELECT id, category, score, total, completed_at FROM practice_sessions WHERE user_id = $1', [userId]),
      this.pool.query('SELECT score, total, completed_at FROM mock_attempts WHERE user_id = $1', [userId]),
      this.pool.query('SELECT ps.category, count(*)::int AS attempts, sum(ps.total)::int AS questions, sum(ps.score)::int AS correct FROM practice_sessions ps WHERE ps.user_id = $1 GROUP BY ps.category', [userId]),
      this.pool.query('SELECT q.topic, count(pa.*)::int AS attempts, count(*) FILTER (WHERE pa.correct)::int AS correct FROM practice_answers pa JOIN practice_sessions ps ON ps.id = pa.session_id JOIN practice_questions q ON q.id = pa.question_id WHERE ps.user_id = $1 GROUP BY q.topic', [userId]),
    ]);
    const tasks = taskResult.rows; const sessions = practiceResult.rows; const mocks = mockResult.rows; const today = new Date(Date.now() - offsetMinutes * 60000).toISOString().slice(0, 10);
    const dateOf = (value) => new Date(new Date(value).getTime() - offsetMinutes * 60000).toISOString().slice(0, 10);
    const taskCompleted = tasks.filter((task) => task.status === 'Completed').length; const pending = tasks.filter((task) => task.status !== 'Completed').length; const overdue = tasks.filter((task) => task.status !== 'Completed' && task.due_date && task.due_date < today).length;
    const practiceQuestions = sessions.reduce((sum, item) => sum + Number(item.total), 0); const practiceCorrect = sessions.reduce((sum, item) => sum + Number(item.score), 0); const mockAverage = mocks.length ? Math.round(mocks.reduce((sum, item) => sum + (item.total ? item.score / item.total * 100 : 0), 0) / mocks.length) : 0;
    const activeDates = new Set([...tasks.filter((item) => item.status === 'Completed' && item.completed_at).map((item) => dateOf(item.completed_at)), ...sessions.map((item) => dateOf(item.completed_at)), ...mocks.map((item) => dateOf(item.completed_at))]); let streak = 0; const cursor = new Date(`${today}T00:00:00Z`); while (activeDates.has(cursor.toISOString().slice(0, 10))) { streak += 1; cursor.setUTCDate(cursor.getUTCDate() - 1); }
    const categories = categoryResult.rows.map((item) => ({ category: item.category, attempted: true, attempts: item.attempts, questions: item.questions, correct: item.correct, accuracy: item.questions ? Math.round(item.correct / item.questions * 100) : 0 })); const strengths = categories.filter((item) => item.questions >= 5 && item.accuracy >= 75).map((item) => item.category); const weakAreas = categories.filter((item) => item.questions >= 5 && item.accuracy < 60).map((item) => item.category);
    const recommendations = []; if (overdue) recommendations.push({ title: 'Complete overdue tasks', description: `${overdue} task${overdue === 1 ? '' : 's'} need attention.`, category: 'Tasks', priority: 'High', action: 'View Tasks' }); if (weakAreas.length) recommendations.push({ title: `Practice ${weakAreas[0]}`, description: 'Your recent accuracy needs more practice.', category: weakAreas[0], priority: 'High', action: 'Start Practice' }); if (!sessions.some((item) => dateOf(item.completed_at) >= dateOf(Date.now() - 3 * 86400000))) recommendations.push({ title: 'Start a practice session', description: 'Keep your preparation momentum moving.', category: 'Practice', priority: 'Medium', action: 'Start Practice' }); if (!mocks.some((item) => dateOf(item.completed_at) >= dateOf(Date.now() - 7 * 86400000))) recommendations.push({ title: 'Take a mock test', description: 'Measure your readiness with a timed simulation.', category: 'Mocks', priority: 'Medium', action: 'View Mock Tests' });
    const totalUnits = practiceQuestions + mocks.reduce((sum, item) => sum + Number(item.total), 0) + tasks.length; const completedUnits = practiceCorrect + mocks.reduce((sum, item) => sum + Number(item.score), 0) + taskCompleted; const progress = totalUnits ? Math.round(completedUnits / totalUnits * 100) : 0;
    const history = new Map(); const historyDay = (date) => { const key = dateOf(date); const item = history.get(key) || { date: key, practiceAccuracy: null, mockScore: null, tasksCompleted: 0 }; history.set(key, item); return item; }; tasks.filter((item) => item.status === 'Completed' && item.completed_at).forEach((item) => { historyDay(item.completed_at).tasksCompleted += 1; }); sessions.forEach((item) => { historyDay(item.completed_at).practiceAccuracy = item.total ? Math.round(item.score / item.total * 100) : 0; }); mocks.forEach((item) => { historyDay(item.completed_at).mockScore = item.total ? Math.round(item.score / item.total * 100) : 0; });
    return { progress: { overallProgress: progress, tasksCompleted: taskCompleted, tasksPending: pending, tasksOverdue: overdue, practiceAttempts: sessions.length, practiceQuestionsAttempted: practiceQuestions, practiceCorrect, practiceAccuracy: practiceQuestions ? Math.round(practiceCorrect / practiceQuestions * 100) : 0, mockTestsCompleted: mocks.length, averageMockScore: mockAverage, currentStreak: streak }, analytics: { overall: { progress, questionsAttempted: practiceQuestions, accuracy: practiceQuestions ? Math.round(practiceCorrect / practiceQuestions * 100) : 0 }, practice: { attempts: sessions.length, accuracy: practiceQuestions ? Math.round(practiceCorrect / practiceQuestions * 100) : 0, averageScore: sessions.length ? Math.round(sessions.reduce((sum, item) => sum + (item.total ? item.score / item.total * 100 : 0), 0) / sessions.length) : 0 }, mock: { completed: mocks.length, averageScore: mockAverage }, tasks: { completed: taskCompleted, pending, overdue }, categories, topics: topicResult.rows.map((item) => ({ topic: item.topic, attempts: item.attempts, correct: item.correct, accuracy: item.attempts ? Math.round(item.correct / item.attempts * 100) : 0 })), strengths, weakAreas, daily: { tasksCompleted: tasks.filter((item) => item.status === 'Completed' && item.completed_at && dateOf(item.completed_at) === today).length, practiceQuestions: sessions.filter((item) => dateOf(item.completed_at) === today).reduce((sum, item) => sum + Number(item.total), 0), practiceSessions: sessions.filter((item) => dateOf(item.completed_at) === today).length, mockTests: mocks.filter((item) => dateOf(item.completed_at) === today).length }, recommendations, performanceHistory: [...history.values()].sort((a, b) => a.date.localeCompare(b.date)) } };
  }
}
module.exports = { PostgresStore, mapUser };
